main = "src/workers/index.ts"
name = "retargetting-platform"

compatibility_date = "2024-06-01"
node_compat = true
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "retargetting"
database_id = "53f8a933-9580-4051-aed6-303d2d90e4ac"

[vars]
D1_ENDPOINT = "${DB.url}"
D1_TOKEN = "${DB.auth_token}"
JWT_SECRET = "changeme"
SESSION_SECRET = "sessionsecret"
TELEGRAM_API_ID = "123456"
TELEGRAM_API_HASH = "your_api_hash"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "7ddd5b1302704448b3e792341d533e19"

